<a href="https://colab.research.google.com/github/nadiia2302/python_for_ds_tasks/blob/main/hw_10_4_apply%2C_groupby%2C_pivot_table.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Домашнє завдання до тем apply(), groupby(), pivot_table()

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
df = pd.read_csv('/content/drive/MyDrive/data/supermarket_sales.csv')

1. Дослідимо, який філіал супермаркету ('Branch') є найприбутковішим. Для цього знайдіть сумарний прибуток за кожним філіалом і виявіть, який філіал має найвищий.

In [4]:
df.groupby("Branch")['Total'].sum().sort_values()

Branch
B    106197.6720
A    106200.3705
C    110568.7065
Name: Total, dtype: float64

Філіал "C" має найвищий сумарний прибуток

Branch “C” has the highest total profit

2. В якому місті знайходиться філіал з найвищим прибутком? Може в тому місці нам розмітисти ще один магазин.  
Знайдіть відповідь за допомогою функціоналу Pandas.

In [5]:
df.groupby(["Branch","City"])['Total'].sum().sort_values()

Branch  City
B       Mandalay     106197.6720
A       Yangon       106200.3705
C       Naypyitaw    110568.7065
Name: Total, dtype: float64

Філіал з найвищим прибутком був в  місті Naypyitaw

The branch with the highest profit was in the city of Naypyitaw

3.1. Створіть зводну таблицю, яка покаже, скільки покупок (інвойсів) було зроблено в кожній з філій (`Branch`) за різними категоріями товарів. Запишіть таблицю в змінну `invoices_by_category` і виведіть змінну на екран.
Ця таблиця допоможе проаналізувати, в якій філії купують найбільше товарів кожної з категорій.

In [16]:
invoices_by_category = pd.pivot_table(df, index = 'Branch', columns = 'Product line', values = 'Quantity',aggfunc = 'size')

In [15]:
invoices_by_category

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Branch,,,,,,
A,60,51,58,47,65,59
B,55,62,50,53,50,62
C,55,65,66,52,45,45

Очікуваний результат:

![](https://drive.google.com/uc?export=view&id=1rueAdko6S3UxIHGtojetTxlES-EyM6Yb)

3.2. Викристовуючи змінну `invoices_by_category` дайте відповідь програмно (тобто значення треба не просто знайти очима, а вивести за допомогою коду), в якому філіалі магазину (`Branch`) найбільше інвойсів із покупкою товарів категорії "Електронні аксесуари" (`Electronic accessories`)?

In [21]:
invoices_by_category['Electronic accessories'].idmax(), invoices_by_category['Electronic accessories'].max()

('A', 60)

In [22]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,20:33,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37,Ewallet,604.17,4.761905,30.2085,5.3

4-6. Творче завдання на розвиток аналітичного мислення

Крок 1. Сформулюйте ТРИ питання (гіпотези) до наявних даних, які допомогли б вам зрозуміти, які користувачі що, де та коли найбільше/найменше купують, аби дати на основі цих гіпотез рекомендації бізнесу. Звісно питання мають бути не тими, на які ми вже відповіли в завданнях модулю.

Крок 2. Знайдіть відповіді на свої питання з допомогою функціоналу pandas.

Крок 3. Напишіть, як відповідь на це питання може бути використана для прийняття бізнес рішень.

Питання можуть бути будь-якої складності, але їх має бути 3. Кожне питання оцінюється як 1 завдання. Без виконання цього завдання ДЗ не приймається. Якщо є питання щодо виконання - пишіть у чат 🙌

Гіпотеза 1. Який тип клієнтів (Member чи Normal) витрачає найбільше коштів на покупки?

In [24]:
df.pivot_table(index = 'Customer type', values = 'Total', aggfunc='sum')

                    Total
Customer type
Member         164223.444
Normal         158743.305

Клієнти, які мають статус Member витрачають найбільше всього грошей на покупки.

Гіпотеза 2. У яку годину дня спостерігається найбільша кількість покупок та найбільша сума продажів?

In [26]:
df['Time'] = pd.to_datetime(df['Time'])

/tmp/ipykernel_1005/2145562215.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'])

In [32]:
df['hours_from_timestamps'] = df['Time'].dt.hour

In [35]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,hours_from_timestamps
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,2026-07-13 13:08:00,Ewallet,522.83,4.761905,26.1415,9.1,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,2026-07-13 10:29:00,Cash,76.40,4.761905,3.8200,9.6,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,2026-07-13 13:23:00,Credit card,324.31,4.761905,16.2155,7.4,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,2026-07-13 20:33:00,Ewallet,465.76,4.761905,23.2880,8.4,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,2026-07-13 10:37:00,Ewallet,604.17,4.761905,30.2085,5.3,10

In [46]:
pivot_by_quantity_and_total = df.pivot_table(index = 'hours_from_timestamps', values = ['Total', 'Quantity'], aggfunc={'Total':'sum','Quantity':'size'})

In [50]:
pivot_by_quantity_and_total.sort_values(['Total', 'Quantity'], ascending=False)

                       Quantity       Total
hours_from_timestamps
19                          113  39699.5130
13                          103  34723.2270
10                          101  31421.4810
15                          102  31179.5085
14                           83  30828.3990
11                           90  30377.3295
12                           89  26065.8825
18                           93  26030.3400
16                           77  25226.3235
17                           74  24445.2180
20                           75  22969.5270

У 19, 13, 10 - х годинах клієнти витрачають найбільше грошей на покупки

Гіпотеза 3. У якому місті та для якої категорії товарів сума продажів є найбільшою?

In [51]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,hours_from_timestamps
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,2026-07-13 13:08:00,Ewallet,522.83,4.761905,26.1415,9.1,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,2026-07-13 10:29:00,Cash,76.40,4.761905,3.8200,9.6,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,2026-07-13 13:23:00,Credit card,324.31,4.761905,16.2155,7.4,13
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,2026-07-13 20:33:00,Ewallet,465.76,4.761905,23.2880,8.4,20
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,2026-07-13 10:37:00,Ewallet,604.17,4.761905,30.2085,5.3,10

In [62]:
pivoted_by_category_city = df.pivot_table(index = 'Product line', columns = 'City', values = ['Total'], aggfunc={'Total':'sum'} )

In [65]:
pivoted_by_category_city

                             Total
City                      Mandalay   Naypyitaw      Yangon
Product line
Electronic accessories  17051.4435  18968.9745  18317.1135
Fashion accessories     16413.3165  21560.0700  16332.5085
Food and beverages      15214.8885  23766.8550  17163.1005
Health and beauty       19980.6600  16615.3260  12597.7530
Home and lifestyle      17549.1645  13895.5530  22417.1955
Sports and travel       19988.1990  15761.9280  19372.6995

У місті Mandalay i Yangon клієнти найбільше витрачають грошей на категорію Sports and travel. У місті Naypyitaw клієнти найбільше втрачають грошей на категорію Naypyitaw